hw finished
Lidemy/mentor-program-5th-weih210287 pull request #4
Opened 2021-04-24 17:06 UTC by weih210287

作業完成了，麻煩助教檢查謝謝 ˊ ˇ ˋ 
另外想請問助教，在開始看教學影片之前自學 JavaScript 時有看到人家說每段的結尾要記得加 `；`，例如：`var str = 'hello';` 但其實後來看 JS101 和其他影片老師也沒有特別說過要加 `；`，而這週在練習後也發現，有加沒加確實沒差。請問這是因為使用的編輯器的關係嗎？還是也是因為 JavaScript 自己有更新過規則了之類的？
雖然也有上網查過了這個問題，但還是很好奇想問一下 😅

2021-04-25 04:08 UTC, cwc329 requested changes
程式題基本要求都有達到，不錯。
給點小建議看要不要再微調一下。
hw6 觀念以及敘述有點不清楚及不完整，請再修正。
如果對函式定義、呼叫的過程不熟悉這次可以不用寫，就寫函式傳入參數之後執行的情形即可。

2021-04-25 04:08 UTC, cwc329 commented on homeworks/week2/hw1.js
> +
多餘的空行最好刪除，檔案末留一行即可。

2021-04-25 04:08 UTC, cwc329 commented on homeworks/week2/hw1.js
> +printStars(6)
呼叫函式如果可以的話在繳交的時候移除，版面會比較乾淨。

2021-04-25 04:08 UTC, cwc329 commented on homeworks/week2/hw5.js
>  }
傳入空陣列的話應該要如何呢？
可以先用 JS 的內建韓式測試看看。

2021-04-25 04:08 UTC, cwc329 commented on homeworks/week2/hw6.md
> +2. 執行第 2 行，設定變數 i = 0，檢查 i 是否 < 陣列 arr 的長度（在這裡 arr.length = 6），是，繼續執行，進入迴圈 1 的第一圈
定義之後就可以直接執行了嗎？

2021-04-25 04:08 UTC, cwc329 commented on homeworks/week2/hw6.md
> +3. 執行第 3 行，檢查 arr[0] 是否 <= 0，不是，繼續往下
arr[0] 是多少呢？

2021-04-25 04:08 UTC, cwc329 commented on homeworks/week2/hw6.md
> +14. 第六圈迴圈結束，回跑第 2 行，i++，i = 6，檢查 i 是否 < 6，不是，迴圈 1 結束，繼續往下（如過程中執行第 3 行時，檢查有任意 arr[i] <= 0，直接回傳 'invalid'）
迴圈結束應該就不會再執行裡面的程式碼了。

2021-04-25 04:23 UTC, cwc329 commented
關於分號的問題，我自己去查了一些資料。
https://hackmd.io/@chupai/B1oMsUZEH
https://262.ecma-international.org/7.0/#sec-rules-of-automatic-semicolon-insertion
針對你的提問，首先這跟你使用的編輯器沒有關係，就算你今天是用筆記本寫 JS，也不會有差別。
JS 自己會先判斷你的程式碼，在他覺得要加分號的地方自己加，基本上這就是我貼的連結在說的事情。
依照我自己去 ECMAScript 的官方文件，在第一版的時候就已經有 automatic semicolon insertion，所以這也不算是 JS 的新規則。
就我自己的想法，教學影片說要加上分號，是要培養一種 coding 的習慣，這會讓人比較好閱讀，因為看到分號就會知道這段程式碼結束了。
不過在寫 JS 的時候要不要每行都加就見仁見智了。
我沒記錯的話，第三週的影片應該會有這個的討論。
以上。

2021-04-25 09:21 UTC, weih210287 commented on homeworks/week2/hw6.md
> +14. 第六圈迴圈結束，回跑第 2 行，i++，i = 6，檢查 i 是否 < 6，不是，迴圈 1 結束，繼續往下（如過程中執行第 3 行時，檢查有任意 arr[i] <= 0，直接回傳 'invalid'）
了解，其實我是想說程式繼續往下到下一階段，沒注意到這個細節
另外謝謝助教對分號的解答，有比較清楚了 ˊ ˇ ˋ

2021-04-25 09:21 UTC, weih210287 commented on homeworks/week2/hw6.md
> +3. 執行第 3 行，檢查 arr[0] 是否 <= 0，不是，繼續往下
arr = [3, 5, 8, 13, 22, 35]
所以 arr[0] = 3

2021-04-25 09:22 UTC, weih210287 commented on homeworks/week2/hw5.js
>  }
不好意思檢查的時候沒注意到這部分
如果傳入空陣列的話會印出空白，所以程式碼應該要變成：
```javascript
function join(arr, concatStr) {
	if(arr.length === 0) {
		return ' '
	}
	for(i = 1; i < arr.length; i++) {
		arr[0] += concatStr + arr[i]
	}
	return arr[0]
}

```

2021-04-25 12:08 UTC, cwc329 commented on homeworks/week2/hw5.js
>  }
是空白嗎？

2021-04-25 12:16 UTC, cwc329 reviewed
有訂正給推！
不過 hw5 反而改錯一個地方，
空白（`' '`）和空字串（`''`）是不同的，最直接的方式是你去看看 `[].join()` 產生的值到底會有什麼性質，並且去看看和哪個相等。

2021-04-25 12:16 UTC, cwc329 commented on homeworks/week2/hw5.js
> +		return ' ';
`' '` 和 `''` 是不一樣的東西。

2021-04-25 17:59 UTC, ClayGao commented on homeworks/week2/hw2.js
>  }
已知 `return` 會跳出整個函式，藉由此點可以寫為：

```js
function capitalize(str) {
	if(str >= 'a' && str <= 'z') {
		return str[0].toUpperCase() + str.slice(1)
	} 
	return str
}
```

2021-04-25 18:01 UTC, ClayGao commented on homeworks/week2/hw5.js
>  	for(i = 1; i < arr.length; i++) {
`for` 裡面建議還是需要宣告 `let i = 1`，否則 `i` 會變因為提升機制宣告在全域範圍中

2021-04-25 18:04 UTC, ClayGao commented on homeworks/week2/hw5.js
>  	for(i = 1; i < arr.length; i++) {
`reverse` 那一題也是，請務必留意 🙏

2021-04-25 18:09 UTC, ClayGao commented
回應一下分號的部分，以這一期來說的 ESlint rules 來說是不用加分號的，但未來加分號還是不加分號，很大的一部分取決你個人或是公司團隊配置，以我目前聽說過實務上不加分號的不在少數，當然加分號的也有，這邊就真的是看個人和團隊了。

2021-04-25 18:09 UTC, merged

2021-04-26 02:11 UTC, weih210287 commented on homeworks/week2/hw5.js
> +		return ' ';
昨天晚上試了一遍，好像有點理解了
使用 join() 回傳出來兩個結果都會是 String，只是差別在當傳入了一個空陣列時結果應該也要是空的 `''`，而不是`' '`。
請問助教這題這樣理解對嗎？

2021-04-26 02:14 UTC, weih210287 commented on homeworks/week2/hw2.js
>  }
好的，謝謝助教 ˊ ˇ ˋ
記得這個部分上課有說到，可是自己檢查的時候卻沒記住 qwq